apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: ecomern-backend
    name: ecommerce-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30008
      protocol: TCP
  type: NodePort
    